spring.application.name=MovieApp_FinalProject
# Server
server.port=8080
spring.security.enabled=false

# H2 Database
spring.datasource.url=jdbc:h2:mem:movie_db
spring.datasource.driverClassName=org.h2.Driver
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# TMDB API
tmdb.api.key=a1e0e93560aead853a677edb68d4a43e
tmdb.api.base-url=https://api.themoviedb.org/3

# Thymeleaf
spring.thymeleaf.cache=false
